name: Test-Build
on:
  push:
    branches:
      - master
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '12.x'
        
    - name: Install newman
      run: npm install -g newman
    
    - name: Make Directory for results
      run: mkdir -p testResults
      
    - name: Run POSTMAN collection
      run: |
        echo "::set-env name=runOutput:: $(newman run ./src/tests/pokemon-api-collection.json -e ./tests/pokemonapi-env.json --reporters cli,json --reporter-json-export output.json)"
        

    # Runs a set of commands using the runners shell
    - name: Echo Response
      run: |
        echo ${{env.runOutput}},
        
